import os
import time
os.system('cls || clear')

print(f"__________________TABUADA DO 1__________________")
print()
for i in range(1, 11):
    print(1, 'X', i, '=', (1*i))
    time.sleep(0.1)
print()
print(f"______________FIM DA TABUADA DO 1______________")
print()
print("////////////////////////////////////////////////////////")
print()

print(f"__________________TABUADA DO 2__________________")
print()
for i in range(1, 11):
    print(2, 'X', i, '=', (2*i))
    time.sleep(0.2)
print()
print(f"______________FIM DA TABUADA DO 2______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 3__________________")
print()
for i in range(1, 11):
    print(3, 'X', i, '=', (3*i))
    time.sleep(0.3)
print()
print(f"______________FIM DA TABUADA DO 3_____________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 4__________________")
print()
for i in range(1, 11):
    print(4, 'X', i, '=', (4*i))
    time.sleep(0.4)
print()
print(f"______________FIM DA TABUADA DO 4______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 5__________________")
print()
for i in range(1, 11):
    print(5, 'X', i, '=', (5*i))
    time.sleep(0.5)
print()
print(f"______________FIM DA TABUADA DO 5______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 6__________________")
print()
for i in range(1, 11):
    print(6, 'X', i, '=', (6*i))
    time.sleep(0.6)
print()
print(f"______________FIM DA TABUADA DO 6______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 7__________________")
print()
for i in range(1, 11):
    print(7, 'X', i, '=', (7*i))
    time.sleep(0.7)
print()
print(f"______________FIM DA TABUADA DO 7______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 8__________________")
print()
for i in range(1, 11):
    print(8, 'X', i, '=', (8*i))
    time.sleep(0.8)
print()
print(f"______________FIM DA TABUADA DO 8______________")
print()
print("////////////////////////////////////////////////////////")
print()

print(f"__________________TABUADA DO 9__________________")
print()
for i in range(1, 11):
    print(9, 'X', i, '=', (9*i))
    time.sleep(0.9)
print()
print(f"______________FIM DA TABUADA DO 9______________")
print()
print("////////////////////////////////////////////////////////")
print()


print(f"__________________TABUADA DO 10__________________")
print()
for i in range(1, 11):
    print(10, 'X', i, '=', (10*i))
    time.sleep(1)
print()
print(f"______________FIM DA TABUADA DO 10______________")


print("""

⠀⣀⣀⣤⣤⣤⣤⣄⣀⣀⠀⠀⢀⣀⣀⣠⣤⣤⣤⣴⣤⣀⠀
⠘⠟⠋⢉⣠⣤⣭⣭⠭⡍⠀⠀⠀⢩⠭⣭⣭⣤⣄⡈⠙⠻⠂
⠀⠀⠴⠯⢽⣿⡿⣹⣍⠟⠀⠀⠀⠻⠸⠏⠿⠿⠧⡽⠂⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠆⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠀⢰⠃⠀⠀
⠀⠀⠀⠀⠀⢠⣀⣀⣀⣀⣀⣀⣀⣀⡤⠤⠞⠁⢀⡏⠀⠀⠀
⠀⠀⠀⠀⠀⠈⠋⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠸⠀⠀⠀⠀




""")
