const listanomes = ["marta", "jose", "diego"]
console.clear()
console.log("exibir todos os elementos")
console.log(listanomes)
console.log()
console.log("exibir um elemento")
console.log(listanomes[1])
console.log()
console.log("adicionar um ser")
listanomes.push("martos")
console.log(listanomes)
console.log()
console.log("eliminar o ultimo ser")
listanomes.pop("martos")
console.log(listanomes)
console.log()
console.log("eliminar o primeiro ser")
listanomes.shift()
console.log(listanomes)